### ISSUE TITLE
Implement stoichiometric inconsistency detection

### ISSUE THREAD

**Issue by phantomas1234** [biosustain/memote#1]
https://www.ncbi.nlm.nih.gov/pubmed/18697772

**Comment by phantomas1234** [comment]
@Midnighter done?

**Comment by Midnighter** [comment]
90% I would like to find a good test for the minimal net stoichiometries (the models linked in the references fell down the 404 hole) and I actually do want to implement the leakage modes. I think, it would be insightful for the report to show which groups of reactions cause an inconsistency.
