### ISSUE TITLE
Check that fluxes (with pFBA) are within reasonable bounds

### ISSUE THREAD

**Issue by Midnighter** [biosustain/memote#3]

**Comment by ChristianLieven** [comment]
Is there a publication that outlines what reasonable bounds for pFBA fluxes are?

**Comment by Midnighter** [comment]
No, this is a bit tricky. I would guess it's relative to the carbon source exchange flux. Maybe we close this issue for now until we come across a useful idea. It doesn't seem terribly important and there are better ways to detect internal cycles or even unbounded solutions.
