### ISSUE TITLE
Develop species specific data import formats for biolog data and gene essentiality data

### ISSUE THREAD

**Issue by ChristianLieven** [biosustain/memote#39]

**Comment by Midnighter** [comment]
This ties in with our discussion with Jon and Wout. We need to support data formats but also a format to formulate tests, like:
take this data, adjust the model, check that the result matches the formulated expectation

**Comment by ChristianLieven** [comment]
I think with based on what we came up with [here](https://github.com/biosustain/memote/pull/105) and [here](https://github.com/biosustain/memote/wiki/Supported-Experimental-Data), we already have this down pretty well.

If there are no objections I'll change PR #105 so that it closes this issue too.

**Comment by Midnighter** [comment]
I'm making a lot of structural changes based on your work in #105. Please don't work on that branch right now.

**Comment by ChristianLieven** [comment]
Reopen if necessary.
