### ISSUE TITLE
make a memote model repository for the whole history of ecoli models

### ISSUE THREAD

**Issue by hredestig** [biosustain/memote#78]
done when: model report website for this repo shows the history of quality of the model over the commits

**Comment by ChristianLieven** [comment]
I made a public repo separate from Biosustain for now, but if @phantomas1234  or @Midnighter  want to take that on, I can transfer ownership of it :)

The report is generated and the growth of the model can be displayed over time! Go check it out here: 
https://christianlieven.github.io/memote-e-coli/

I consider this issue done!
